'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents Menu1 As Global.TCC.Menu
    Protected WithEvents txtLogin As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtSenha As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnLogar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents Login As Label
    Protected WithEvents Senha As Label
    Protected WithEvents lblError As Label
End Class
