'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Pacote1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents Menu1 As Global.TCC.Menu
    Protected WithEvents txtPacote As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPreco As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnGravar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnExcluir As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAlterar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents Descricao As Global.System.Web.UI.WebControls.Label
    Protected WithEvents Preco As Global.System.Web.UI.WebControls.Label
End Class
